version: '3.8'

services:
  postgres:
    container_name: some-postgres-node
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: "dev"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
